---
title: "Getting started"
format: 
  html:
    toc: true
    toc-depth: 2
execute:
  freeze: false
bibliography: bibliography.bib
nocite: |
  @Louden2020-ym, @Schriml2012-kn, @Kundra2021-xu, 
  @Malone2010-vu, @Huang2018-ah
---

<br><br>


## Installation

```{r}
#| echo: true
#| eval: false

if (!("remotes" %in% installed.packages())) {
 install.packages("remotes")
}
remotes::install_github('sigven/phenOncoX')
```


<br><br>

## Core OncoTree terms

This shows how to retrieve cancer phenotype terms in, as defined in 
[OncoTree](http://oncotree.mskcc.org/#/home) (*max tree depth* = 2)

```{r core}
#| echo: true

## load the data
download_dir <- tempdir()

oncotree <- phenOncoX::get_tree(
  cache_dir = download_dir, max_tree_depth = 2)

## Number of records
nrow(oncotree$records)

## Show metadata for underlying resources
oncotree$metadata


```

<br><br>

## Cancer phenotype terms

```{r expanded}
#| echo: true
#| eval: true

## get all cancer phenotype terms - OncoTree-expanded 
oncoterms <- phenOncoX::get_terms(
  cache_dir = download_dir)

## Number of records
nrow(oncoterms$records)


```

<br><br>

## Term statistics per primary tumor type/tissue

```{r num_terms_per_tissue}
#| echo: true
#| eval: true

## get all cancer phenotype terms
oncoterms <- phenOncoX::get_terms(
  cache_dir = download_dir)

## Number of records
as.data.frame(oncoterms$records |>
  dplyr::filter(!is.na(primary_site)) |>
  dplyr::group_by(primary_site) |> 
  dplyr::summarise(num_terms = dplyr::n(),
                   .groups = "drop") |>
  dplyr::arrange(dplyr::desc(num_terms)))

```



## Terms relevant for prostate cancer 

```{r terms_prostate}
#| echo: true
#| eval: true
#| results: "hide"

## get all oncoterms for prostate cancer
oncoterms_prostate <- phenOncoX::get_terms(
  cache_dir = download_dir, 
  site = "Prostate")

# ## Make as datatable
# prostate_terms_table <- DT::datatable(
#   dplyr::select(
#     oncoterms_prostate$records, 
#     primary_site, cui, cui_name,
#     dplyr::everything()),
#   escape = FALSE,
#   extensions = c("Buttons", "Responsive"), 
#   width = "100%",
#   options = list(
#     buttons = c("csv", "excel"), 
#     dom = "Bfrtip"))

prostate_terms_table <- reactable::reactable(
  dplyr::select(
    oncoterms_prostate$records, 
    primary_site, cui, cui_name,
    dplyr::everything()),
  filterable = TRUE,
  sortable = TRUE,
  striped = TRUE,
  compact = TRUE,
  searchable = TRUE,
  defaultPageSize = 10
  #downloadable = TRUE
)

```

<br>

```{r prostate_terms_table}
#| echo: false
#| eval: true
prostate_terms_table
```

<br><br>

# Session Info

```{r sessioninfo}
#| eval: true
#| echo: true

sessionInfo()
```

<br><br>

# References